### ISSUE TITLE
Please fix the authorized_keys typo in Setting Up and Login In to an EC2 Instance (AWS)

### ISSUE THREAD

**Issue by achshar** [juanfrans/notes#1]
https://github.com/juanfrans/notes/wiki/Setting-Up-and-Login-In-to-an-EC2-Instance-(AWS)

Creating New Users

**Comment by juanfrans** [comment]
@achshar Where exactly is the typo?

**Comment by achshar** [comment]
Ctrl + F "(Remote) Edit the authorized_key file with a text editor (ie. Nano) " twice on the same line.

**Comment by juanfrans** [comment]
@achshar, done. Thank you.
